# Generated by Django 3.1.2 on 2021-01-06 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_auto_20201222_0711'),
    ]

    operations = [
        migrations.CreateModel(
            name='AvailableDataType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='organization',
            name='data_types',
            field=models.ManyToManyField(to='core.AvailableDataType'),
        ),
    ]
