# Generated by Django 3.1.2 on 2020-12-24 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_auto_20201222_0711'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materialdemand',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='materialdemand',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
