# Generated by Django 3.1.2 on 2020-12-24 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_auto_20201224_1718'),
    ]

    operations = [
        migrations.AddField(
            model_name='materialdemand',
            name='availability',
            field=models.CharField(choices=[('unavailable', 'unavailable'), ('occasionally', 'occasionally available'), ('short-term', 'available short-term use'), ('long-term', 'available for long-term use')], max_length=50, null=True),
        ),
    ]
