# Generated by Django 3.1.2 on 2021-01-04 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_materialdemand_availability'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materialdemand',
            name='availability',
            field=models.CharField(blank=True, choices=[('unavailable', 'unavailable'), ('occasionally', 'occasionally available'), ('short-term', 'available short-term use'), ('long-term', 'available for long-term use')], max_length=50, null=True),
        ),
    ]
